__a(s); for(int i=1; i<=9; i++) { __a(s); } for(int j=1; j<=9; j++) { __a(s); }
</think>

#include<cuda55/cu.h>
#include<cuda55/iostream.h>
#include<cuda55/algorithm.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<cuda55/arith.h>
#include<