#include <iostream>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <assertion>
#include <climits>
#include <cmath>
#include <climits>
#include <cmath>
#include <climits>
#include <cmath>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits>
#include <climits
#include <cl