Your code should be 100% accurate.
</think>

cpp
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <iomanip>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>
#include <cmath>