#include <iostream>
#include <vector>
#include <list>
#include <map>
#include<string>
#include <algorithm>
#include <functional>
#include <cmath>
using namespace std;
#include <cuda.h>
#include <cuda_runtime>
using namespace std;
#include <cuda Device>
#include <cuda Memory>
#include <cuda Stream>
#include <cuda Kernel>
#include <cuda Stream Manager>
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <cuda Stream Manager>...
#include <