cpp
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_gemm.h>
#include <cuda_runtime_gemm_kernel.h>
#include <cuda_runtime_gemm_fprop.h>
#include <cuda_runtime_gemm_transf.h>
#include <cuda_runtime_gemm_cvt.h>
#include <cuda_runtime_gemm_sse2.h>
#include <cuda_runtime_gemm_sse3.h>
#include <cuda_runtime_gemm_sse4.h>
#include <cuda_runtime_gemm_sse5.h>
#include <cuda_runtime_gemm_sse6.h>
#include <cuda_runtime_gemm_sse7.h>
#include <cuda_runtime_gemm_sse8.h>
#include <cuda_runtime_gemm_sse9.h>
#include <cuda_runtime_gemm_sse10.h>
#include <cuda_runtime_gemm_sse11.h>
#include <cuda_runtime_gemm_sse12.h>
#include <cuda_runtime_gemm_sse13.h>
#include <cuda_runtime_gemm_sse14.h>
#include <cuda_runtime_gemm_sse15.h>
#include <cuda_runtime_gemm_sse16.h>
#include <cuda_runtime_gemm_sse17.h>
#include <cuda_runtime_gemm_sse18.h>
#include <cuda_runtime_gemm_sse19.h>
#include <cuda_runtime_gemm_sse20.h>
#include <cuda_runtime_gemm_sse21.h>
#include <cuda_runtime_gemm_sse22.h>
#include <cuda_runtime_gemm_sse23.h>
#include <cuda_runtime_gemm_sse24.h>
#include <cuda_runtime_gemm_sse25.h>
#include <cuda_runtime_gemm_sse26.h>
#include <cuda_runtime_gemm_sse27.h>
#include <cuda_runtime_gemm_sse28.h>
#include <cuda_runtime_gemm_sse29.h>
#include <cuda_runtime_gemm_sse30.h>
#include <cuda_runtime_gemm_sse31.h>
#include <cuda_runtime_gemm_sse32.h>
#include <cuda_runtime_gemm_sse33.h>
#include <cuda_runtime_gemm_sse34.h>
#include <cuda_runtime_gemm_sse35.h>
#include <cuda_runtime_gemm_sse36.h>
#include <cuda_runtime_gemm_sse37.h>
#include <cuda_runtime_gemm_sse38.h>
#include <cuda_runtime_gemm_sse39.h>
#include