ssert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstdio>
#include <cstdlib>
#include <cstdio>
#include <cstdlib>
#include <cstdio>
#include <cstdlib>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio>
#include <cstdio