>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <