ude <cstring>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include <cstring>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include <cstring>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdlib>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cstdio>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <cassert>
#include <