ude<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cmath>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<cctype>
#include<cassert>
#