include<cctype>
#include<cassert>
#include<ctime>
#include<cstdio>
#include<cmath>
#include<cstdlib>
#include<cassert>
#include<cstdio>
#include<cstdlib>
#include<cassert>
#include<cstdio>
#include<cstdio>
#include<cassert>
#include<cstdio>
#include<cassert>
#include<cstdio>
#include<cassert>
#include<cstdio>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include<cassert>
#include