#include <vector>
#include <string>
#include <sstream>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <algorithm