__global__ void main() {
  __global__ void main() {
    __global__ void main() {
      __global__ void main() {
        __global__ void main() {
          __global__ void main() {
            __global__ void main() {
              __global__ void main() {
                __global__ void main() {
                  __global__ void main() {
                    __global__ void main() {
                      __global__ void main() {
                        __global__ void main() {
                          __global__ void main() {
                            __global__ void main() {
                              __global__ void main() {
                                __global__ void main() {
                                  __global__ void main() {
                                    __global__ void main() {
                                      __global__ void main() {
                                        __global__ void main() {
                                          __global__ void main() {
                                            __global__ void main() {
                                              __global__ void main() {
                                                __global__ void main() {
                                                  __global__ void main() {
                                                    __global__ void main() {
                                                      __global__ void main() {
                                                        __global__ void main() {
                                                          __global__ void main() {
                                                            __global__ void main() {
                                                              __global__ void main() {
                                                                __global__ void main() {
                                                                  __global__ void main() {
                                                                    __global__ void main() {
                                                                      __global__ void main() {
                                                                        __global__ void main() {
                                                                          __global__ void main() {
                                                                            __global__ void main() {
                                                                              __global__ void main() {
                                                                                __global__ void main() {
                                                                                  __global__ void main() {
                                                                                    __global__ void main() {
                                                                                      __global__ void main() {
                                                                                        __global__ void main() {
                                                                                          __global__ void main() {
                                                                                            __global__ void main() {
                                                                                              __global__ void main() {
                                                                                                __global__ void main() {
                                                                                                  __global__ void main() {
                                                                                                    __global__ void main() {
                                                                                                      __global__ void main() {
                                                                                                        __global__ void main() {
                                                                                                          __global__ void main() {
                                                                                                            __global__ void main() {
                                                                                                              __global__ void main() {
                                                                                                                __global__ void main() {
                                                                                                                  __global__ void main() {
                                                                                                                    __global__ void main() {
                                                                                                                      __global__ void main() {
                                                                                                                        __global__ void main() {
                                                                                                                          __global__ void main