#include <cuda_runtime.h>
#include <vector>
#include <cstddef>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstring>
#include <cmath>
#include <vector>
#include <algorithm>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>
#include <map>
#include <set>