#include <vector>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>
#include <cctype>
#include <cassert>
#include <cstdio>
#include <algorithm>
#include <map>
#include <deque>
#include <cstring>
#include <climits>