#include <vector>
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include