#include <stdio.h>
#include <math.h>
#include <vector>
#include <stack>
#include <queue>
#include <list>
#include <sstream>
#include <string>
#include <cstdlib>
#include <algorithm>
#include <vector>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include