cpp
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_gemm.h>
#include <cuda_runtime_gemm_kernel.h>
#include <cuda_runtime_gemm_fprop.h>
#include <cuda_runtime_gemm_transf.h>
#include <cuda_runtime_gemm_cwise_func.h>
#include <cuda_runtime_gemm_cwise_grad.h>
#include <cuda_runtime_gemm_cwise_scale.h>
#include <cuda_runtime_gemm_cwise_subtract.h>
#include <cuda_runtime_gemm_cwise_add.h>
#include <cuda_runtime_gemm_cwise_max.h>
#include <cuda_runtime_gemm_cwise_min.h>
#include <cuda_runtime_gemm_cwise_product.h>
#include <cuda_runtime_gemm_cwise_divide.h>
#include <cuda_runtime_gemm_cwise_multiply.h>
#include <cuda_runtime_gemm_cwise_subtract.h>
#include <cuda_runtime_gemm_cwise_add.h>
#include <cuda_runtime_gemm_cwise_max.h>
#include <cuda_runtime_gemm_cwise_min.h>
#include <cuda_runtime_gemm_cwise_product.h>
#include <cuda_runtime_gemm_cwise_divide.h>
#include <cuda_runtime_gemm_cwise_multiply.h>
#include <cuda_runtime_gemm_cwise_subtract.h>
#include <cuda_runtime_gemm_cwise_add.h>
#include <cuda_runtime_gemm_cwise_max.h>
#include <cuda_runtime_gemm_cwise_min.h>
#include <cuda_runtime_gemm_cwise_product.h>
#include <cuda_runtime_gemm_cwise_divide.h>
#include <cuda_runtime_gemm_cwise_multiply.h>
#include <cuda_runtime_gemm_cwise_subtract.h>
#include <cuda_runtime_gemm_cwise_add.h>
#include <cuda_runtime_gemm_cwise_max.h>
#include <cuda_runtime_gemm_cwise_min.h>
#include <cuda_runtime_gemm_cwise_product.h>
#include <cuda_runtime_gemm_cwise_divide.h>
#include <cuda_runtime_gemm_cwise_multiply.h>
#include <cuda_runtime_gemm_cwise_subtract.h>
#include <cuda_runtime_gemm_cwise_add.h>
#include <cuda_runtime_gemm_cwise_max.h>
#include <cuda_runtime_gemm_cwise_min.h>
#include <cuda_runtime_gemm_cwise_product.h>
#include <cuda_runtime_gemm_cwise_divide.h>
#include <cuda_runtime_gemm_cwise_multiply.h>
#include <cuda_runtime_gemm_cwise_subtract.h>
#include <cuda_runtime_gemm_cwise_add.h>
#include <cuda_runtime_gemm_c