#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <unistd.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include <cuda_runtime_api.h>
#include